### ISSUE TITLE
Adding presets

### ISSUE THREAD

**Issue by robouden** [jeanslack/Videomass-presets#4]
Hi,

I like to add some presets for Davinci Resolve conversions for Linux.
How to do that?

Regards,
rob Oudendijk

**Comment by robouden** [comment]
Davinci Resolve Linux preset:
[
    {
        "Name": "Davinci resolve convert",
        "Description": "Davinci resolve convert",
        "First_pass": "-vcodec mjpeg -q:v 2 -acodec pcm_s16be -q:a 0 -f mov",
        "Second_pass": "",
        "Supported_list": "",
        "Output_extension": "mov"
    }
]

**Comment by robouden** [comment]
Hi,

Seems your repo is read only.
Maybe you can pull from my repo at
https://github.com/robouden/VideoMass_presets?

Regards,
rob

**Comment by johannesdedoper** [comment]
I also use DV Resolve on Linux. Nice.
Normally you just have to encode the audio.
That are my presets to copy the video and convert audio only to PCM.
Because of the audio in PCM most of the times the file gets bigger but I want to be sure none of the video/audio quality gets lost.
This way video is NOT encoded and audio is encoded in the highest quality.
Furthermore this is very fast, takes only a few seconds per file.
Also you can use the MKV or MOV container, DVR will work with both.

`-c:v copy -c:a pcm_s16le -c:s copy`

cheers.
J.

**Comment by jeanslack** [comment]
>  your repo is read only.
Maybe you can pull from my repo at
https://github.com/robouden/VideoMass_presets?

@robouden 

If you only have the preset you posted [here](https://github.com/jeanslack/Videomass-presets/issues/4#issuecomment-1598681222), don't pull request now please. As soon as I have some more time I will add it to the presets list and send you the link in this post.

Thank you for sharing your preset!

**Comment by jeanslack** [comment]
Hi, Sorry if I'm late,

@johannesdedoper 
I have made a selection of your `NVidia accelerated video encoding` presets and have posted them [here](https://github.com/jeanslack/Videomass-presets/tree/master/NVidia%20accelerated%20video%20encoding), they may be useful for some users.

@robouden 
I've added a new folder containing your [Davinci Resolve Linux preset](https://github.com/jeanslack/Videomass-presets/tree/master/Davinci%20Resolve%20Linux). Feel free to add new profiles related to the Davinci Resolve Linux preset using the `.prst` file inside that folder.
I've also created a new wiki page (work in progress) which will contain [Guidelines for sharing Videomass presets](https://github.com/jeanslack/Videomass-presets/wiki/Guidelines-for-sharing-Videomass-presets).

Thanks a lot to both!

**Comment by robouden** [comment]
Jean,

Better late than not.

Warm regards,
Rob Oudendijk
